require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'starter' do
# React Native Maps dependencies

  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'FlipperKit/Core', '~> 0.74.0'
  pod 'FlipperKit/FlipperKitReactPlugin', '~> 0.74.0'
  pod 'FlipperKit/FlipperKitLayoutPlugin', '~> 0.74.0'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', '~> 0.74.0'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', '~> 0.74.0'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', '~> 0.74.0'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~> 0.74.0'
  pod 'FlipperKit/FlipperKitNetworkPlugin', '~> 0.74.0'
  pod 'FlipperKit/FBDefines', '~> 0.74.0'
  pod 'Flipper-RSocket', '~> 1.1'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 6.4.0'
  pod 'Firebase/Analytics'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'starterTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({'Flipper' => '0.74.0'})

  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'starter-tvOS' do
  # Pods for starter-tvOS

  target 'starter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
